version: "3.8"


services:
  web:
    build: .
    command: ["python" ,"manage.py" ,"runserver","0.0.0.0:8000"]
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped


  worker:
    build: .
    command: celery -A django_task worker -l info
    depends_on:
      - redis
      - database
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  database:
    image: postgres:15-alpine
    container_name: employee_data
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: