# Generated by Django 6.0.1 on 2026-01-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("monthly_salary", models.IntegerField()),
                ("approved_limit", models.IntegerField()),
                ("current_debt", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoanData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_id", models.IntegerField()),
                ("loan_amount", models.IntegerField()),
                ("tenure", models.IntegerField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=4)),
                ("monthly_repayment", models.IntegerField()),
                ("EMIs_paid_on_time", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="credit.customerdata",
                    ),
                ),
            ],
        ),
    ]
